# Generated by Django 4.2 on 2025-06-21 15:08

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Endereço de e-mail único do usuário', max_length=254, unique=True, verbose_name='Email')),
                ('nome', models.CharField(help_text='Nome completo do usuário', max_length=150, verbose_name='Nome Completo')),
                ('endereco', models.TextField(blank=True, help_text='Endereço de entrega padrão do usuário', verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, help_text='Número de telefone de contato', max_length=17, validators=[django.core.validators.RegexValidator(message="Número de telefone deve estar no formato: '+999999999'.             Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora do registro do usuário', verbose_name='Data de Cadastro')),
                ('is_admin', models.BooleanField(default=False, help_text='Indica se o usuário tem privilégios administrativos', verbose_name='Administrador')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
