# Generated by Django 4.2 on 2025-06-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-registration_date'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='endereco',
            new_name='adrress',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telefone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='data_cadastro',
            new_name='registration_date',
        ),
    ]
