# Generated by Django 4.2 on 2025-06-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_rename_endereco_user_adrress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adrress',
            new_name='address',
        ),
    ]
