version: "3.9"

services:
  web:
    build: .
    command: pytest --cov=reviews --cov-report=term-missing -v
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.test
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
