services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user -d django_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: >
      bash -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/home/django/app
      - ./static:/home/django/app/static
      - ./media:/home/django/app/media
      - ./logs:/home/django/app/logs
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://django_user:django_password@db:5432/django_db
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=petstore.settings
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    stdin_open: true
    tty: true

  celery:
    build: .
    command: >
      bash -c "python manage.py wait_for_db &&
               celery -A config worker --loglevel=info"
    volumes:
      - ./:/home/django/app
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://django_user:django_password@db:5432/django_db
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - db
      - redis

  test:
    build: .
    command: >
      bash -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               pytest --maxfail=1 --disable-warnings -q --cov=/home/django/app --cov-report=term-missing --cov-report=html:/home/django/app/htmlcov"
    working_dir: /home/django/app
    volumes:
      - ./:/home/django/app
      - htmlcov:/home/django/app/htmlcov
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DATABASE_URL: postgres://django_user:django_password@db:5432/django_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
  htmlcov:
  