# Generated by Django 4.2 on 2025-06-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do produto', max_length=255, verbose_name='Nome')),
                ('description', models.TextField(help_text='Descrição detalhada do produto', verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço unitário do produto', max_digits=10, verbose_name='Preço')),
                ('stock', models.PositiveIntegerField(help_text='Quantidade disponível em estoque', verbose_name='Estoque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('active', models.BooleanField(default=True, help_text='Indica se um produto está visível e disponível para venda', verbose_name='Ativo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produos',
                'ordering': ['-created_at'],
            },
        ),
    ]
