# Generated by Django 5.2.3 on 2025-08-07 13:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do pedido', primary_key=True, serialize=False)),
                ('order_data', models.DateField(default=django.utils.timezone.now, help_text='Data e hora que o pedido foi realizado', verbose_name='Data do Pedido')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', ' Cancelado')], help_text='Status atual do pedido', max_length=20, verbose_name='Status')),
                ('total', models.DecimalField(decimal_places=2, help_text='Valor total do pedido', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total')),
                ('shipping_address', models.TextField(help_text='Endereço completo para envio do pedido', max_length=500, verbose_name='Endereço de Envio')),
                ('payment_method', models.CharField(choices=[('cartão_crédito', 'Cartão de Crédito'), ('cartão_debito', 'Cartão de Débito'), ('boleto', 'Boleto Bancário'), ('pix', 'PIX'), ('dinheiro', 'Dinheiro')], help_text='Método de pagamento utilizado', max_length=20, verbose_name='Método de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(help_text='Usuário que realizou o pedido', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-order_data'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único para intens do pedido.', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Quantidade de produto no pedido', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at the same time of purchase (important for history)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Unit Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('order', models.ForeignKey(help_text='Pedido ao qual este item pertence', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Ordem')),
                ('product', models.ForeignKey(help_text='Pedido do produto', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_data'], name='orders_orde_order_d_59c922_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product_id'], name='orders_orde_product_32ff41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
