# Generated by Django 5.2.3 on 2025-08-04 16:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do pedido', primary_key=True, serialize=False)),
                ('order_data', models.DateField(default=django.utils.timezone.now, help_text='Data e hora que o pedido foi realizado', verbose_name='Data do Pedido')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', ' Cancelado')], help_text='Status atual do pedido', max_length=20, verbose_name='Status')),
                ('total', models.DecimalField(decimal_places=2, help_text='Valor total do pedido', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total')),
                ('shipping_address', models.TextField(help_text='Endereço completo para envio do pedido', max_length=500, verbose_name='Endereço de Envio')),
                ('payment_method', models.CharField(choices=[('cartão_crédito', 'Cartão de Crédito'), ('cartão_debito', 'Cartão de Débito'), ('boleto', 'Boleto Bancário'), ('pix', 'PIX'), ('dinheiro', 'Dinheiro')], help_text='Método de pagamento utilizado', max_length=20, verbose_name='Método de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(help_text='Usuário que realizou o pedido', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-order_data'],
                'indexes': [models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'), models.Index(fields=['order_data'], name='orders_orde_order_d_59c922_idx'), models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx')],
            },
        ),
    ]
