# Generated by Django 4.2 on 2025-06-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual de desconto a ser aplicado', max_digits=5, verbose_name='Desconto (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de unidades vendidas deste produto', verbose_name='Unidades Vendidas'),
        ),
    ]
