# Generated by Django 4.2 on 2025-06-27 19:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='quantidade em estoque')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='peso (kg)')),
                ('idade_recomendada', models.CharField(blank=True, help_text='Ex: Filhote, Adulto, Idoso, Todas as idades', max_length=50, verbose_name='idade recomendada')),
                ('especie', models.CharField(blank=True, help_text='Ex: Cão, Gato, Pássaro, Peixe, etc.', max_length=50, verbose_name='espécie')),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='imagem principal')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('destaque', models.BooleanField(default=False, verbose_name='produto em destaque')),
                ('promocao', models.BooleanField(default=False, verbose_name='em promoção')),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço promocional')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='código de barras')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit - Código interno do produto', max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='products.categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='products/gallery/', verbose_name='imagem')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_adicionais', to='products.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'imagem do produto',
                'verbose_name_plural': 'imagens dos produtos',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['nome'], name='products_pr_nome_5e3524_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['categoria'], name='products_pr_categor_944176_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ativo'], name='products_pr_ativo_ddb860_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['destaque'], name='products_pr_destaqu_34813f_idx'),
        ),
    ]
