# Generated by Django 4.2 on 2025-06-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_discount_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='Marque para exibir esta categoria na página inicial', verbose_name='Em destaque'),
        ),
    ]
