# Generated by Django 5.2.3 on 2025-07-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Nome"),
        ),
    ]
