# Generated by Django 5.2.3 on 2025-07-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Nome"),
        ),
    ]
